// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9VlrMpyKqApX8BC6qNAlBDFnXzdQCcs',
    appId: '1:441378487264:web:a456728afbee1e04cfc985',
    messagingSenderId: '441378487264',
    projectId: 'julio-nfc-manager',
    authDomain: 'julio-nfc-manager.firebaseapp.com',
    storageBucket: 'julio-nfc-manager.firebasestorage.app',
    measurementId: 'G-Y2VPVPEY51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGAoC5TbDkzY920cBKOEoslX2o_hrpE9M',
    appId: '1:441378487264:android:f5cc1ce6f0bd4931cfc985',
    messagingSenderId: '441378487264',
    projectId: 'julio-nfc-manager',
    storageBucket: 'julio-nfc-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3ksNvrx7AzUU5lm1glsaYbV9GqeaS88',
    appId: '1:441378487264:ios:f447f6c8fa081e35cfc985',
    messagingSenderId: '441378487264',
    projectId: 'julio-nfc-manager',
    storageBucket: 'julio-nfc-manager.firebasestorage.app',
    iosClientId: '441378487264-q3ceinodtanh9dn6fn9ancp9ds7f4a5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.julioNfcManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3ksNvrx7AzUU5lm1glsaYbV9GqeaS88',
    appId: '1:441378487264:ios:f447f6c8fa081e35cfc985',
    messagingSenderId: '441378487264',
    projectId: 'julio-nfc-manager',
    storageBucket: 'julio-nfc-manager.firebasestorage.app',
    iosClientId: '441378487264-q3ceinodtanh9dn6fn9ancp9ds7f4a5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.julioNfcManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG9VlrMpyKqApX8BC6qNAlBDFnXzdQCcs',
    appId: '1:441378487264:web:477ba3aa1b1fb4d6cfc985',
    messagingSenderId: '441378487264',
    projectId: 'julio-nfc-manager',
    authDomain: 'julio-nfc-manager.firebaseapp.com',
    storageBucket: 'julio-nfc-manager.firebasestorage.app',
    measurementId: 'G-E1GYVZTQTQ',
  );
}
